///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("85873dfb-4cb3-47b2-a32e-f1578a77fa0b")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTestRepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder _họcliệusachmềmgooglechrome;
        MyTestRepositoryFolders.HọcLiệuSachMềmAppFolder _họcliệusachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("85873dfb-4cb3-47b2-a32e-f1578a77fa0b")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "85873dfb-4cb3-47b2-a32e-f1578a77fa0b", ".\\RepositoryImages\\MyTestRepository85873dfb.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _họcliệusachmềmgooglechrome = new MyTestRepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder(this);
            _họcliệusachmềm = new MyTestRepositoryFolders.HọcLiệuSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("85873dfb-4cb3-47b2-a32e-f1578a77fa0b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("2c8c8cfe-a842-414d-a766-bf8f3d367ba6")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("5cad0c60-c7d0-49d9-b14c-44f9b77737ae")]
        public virtual MyTestRepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder HọcLiệuSachMềmGoogleChrome
        {
            get { return _họcliệusachmềmgooglechrome; }
        }

        /// <summary>
        /// The HọcLiệuSachMềm folder.
        /// </summary>
        [RepositoryFolder("6c5492f8-9a4f-47b8-b3b9-7f8809f32dd1")]
        public virtual MyTestRepositoryFolders.HọcLiệuSachMềmAppFolder HọcLiệuSachMềm
        {
            get { return _họcliệusachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("2c8c8cfe-a842-414d-a766-bf8f3d367ba6")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder _httpshoclieusachmemvnquestionset;
            MyTestRepositoryFolders.ContentBoundFolder _contentbound;
            RepoItemInfo _giaobaitậpInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, true, "2c8c8cfe-a842-414d-a766-bf8f3d367ba6", "")
            {
                _httpshoclieusachmemvnquestionset = new MyTestRepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder(this);
                _contentbound = new MyTestRepositoryFolders.ContentBoundFolder(this);
                _giaobaitậpInfo = new RepoItemInfo(this, "GiaoBaiTập", "body/tag[@tagname='app-root']/div[2]//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div/div[1]/div[2]/a[@href='javascript:void(0)']/span[@innertext='Giao bài tập']", 30000, null, "cdbc43fd-c48f-4810-a07e-fe2e25b45235");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2c8c8cfe-a842-414d-a766-bf8f3d367ba6")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2c8c8cfe-a842-414d-a766-bf8f3d367ba6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiaoBaiTập item.
            /// </summary>
            [RepositoryItem("cdbc43fd-c48f-4810-a07e-fe2e25b45235")]
            public virtual Ranorex.SpanTag GiaoBaiTập
            {
                get
                {
                    return _giaobaitậpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GiaoBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("cdbc43fd-c48f-4810-a07e-fe2e25b45235")]
            public virtual RepoItemInfo GiaoBaiTậpInfo
            {
                get
                {
                    return _giaobaitậpInfo;
                }
            }

            /// <summary>
            /// The HttpsHoclieuSachmemVnQuestionSet folder.
            /// </summary>
            [RepositoryFolder("43d5559f-b64d-4596-8b96-712b5f82ee59")]
            public virtual MyTestRepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder HttpsHoclieuSachmemVnQuestionSet
            {
                get { return _httpshoclieusachmemvnquestionset; }
            }

            /// <summary>
            /// The ContentBound folder.
            /// </summary>
            [RepositoryFolder("3b3d24bf-c24e-4590-9722-1bd2a2b854b8")]
            public virtual MyTestRepositoryFolders.ContentBoundFolder ContentBound
            {
                get { return _contentbound; }
            }
        }

        /// <summary>
        /// The HttpsHoclieuSachmemVnQuestionSetFolder folder.
        /// </summary>
        [RepositoryFolder("43d5559f-b64d-4596-8b96-712b5f82ee59")]
        public partial class HttpsHoclieuSachmemVnQuestionSetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;
            RepoItemInfo _modalbodyInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _formgroupInfo;
            RepoItemInfo _ngoptionngoptionmarkedngstarinserInfo;
            RepoItemInfo _text2Info;
            RepoItemInfo _text1Info;
            RepoItemInfo _noitemsfoundInfo;
            RepoItemInfo _text3Info;
            RepoItemInfo _testclassInfo;
            RepoItemInfo _numberInfo;
            RepoItemInfo _number1Info;
            RepoItemInfo _labeltagtrộncauhỏiInfo;
            RepoItemInfo _formcheckInfo;

            /// <summary>
            /// Creates a new HttpsHoclieuSachmemVnQuestionSet  folder.
            /// </summary>
            public HttpsHoclieuSachmemVnQuestionSetFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsHoclieuSachmemVnQuestionSet", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']", parentFolder, 30000, null, false, "43d5559f-b64d-4596-8b96-712b5f82ee59", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", "?/?/input[@type='submit']", 30000, null, "086b6bc2-2a40-4e20-b12e-dd9548a4e251");
                _modalbodyInfo = new RepoItemInfo(this, "ModalBody", "div[1]", 30000, null, "bfd04f86-3cec-4d42-b2b7-29aff6dc6ac8");
                _textInfo = new RepoItemInfo(this, "Text", "div[1]/div[2]/input[@type='text']", 30000, null, "f5ed13d9-9bfb-47ae-85e8-8ec28308e2cb");
                _formgroupInfo = new RepoItemInfo(this, "FormGroup", "div[1]/div[3]", 30000, null, "74a5b92a-f471-4d38-b5af-eca45d82db85");
                _ngoptionngoptionmarkedngstarinserInfo = new RepoItemInfo(this, "NgOptionNgOptionMarkedNgStarInser", "div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div", 30000, null, "aa92ed90-c631-49dd-bb57-1010f783a4fe");
                _text2Info = new RepoItemInfo(this, "Text2", "div[1]/div[3]/tag[@tagname='ng-select']/div//input[@type='text']", 30000, null, "df40a9c2-18d5-47f4-bbcc-f94969f2d501");
                _text1Info = new RepoItemInfo(this, "Text1", "div[1]/div[3]/tag[@tagname='ng-select']/div/div/?/?/input[@type='text']", 30000, null, "99d5160c-05ee-4843-803e-c71c11006a2a");
                _noitemsfoundInfo = new RepoItemInfo(this, "NoItemsFound", "div[1]/div[4]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div[@innertext='No items found']", 30000, null, "30fe938d-acd7-46e0-9212-71c003f01506");
                _text3Info = new RepoItemInfo(this, "Text3", "div[1]/div[4]/tag[@tagname='ng-select']/div/div/?/?/input[@type='text']", 30000, null, "a6b15461-651d-489f-beb7-261573e1081b");
                _testclassInfo = new RepoItemInfo(this, "TestClass", "div[1]/div[5]/select[@name='test-class']", 30000, null, "94561733-7903-469b-9329-f175b8c2e905");
                _numberInfo = new RepoItemInfo(this, "Number", "div[1]/div[6]/input[@type='number']", 30000, null, "6b2bebca-4952-408f-b6bb-ec474d542f3c");
                _number1Info = new RepoItemInfo(this, "Number1", "div[1]/div[7]/input[@type='number']", 30000, null, "5ff30eec-c807-4d19-b0b1-7dd0cc810aec");
                _labeltagtrộncauhỏiInfo = new RepoItemInfo(this, "LabelTagTrộnCauHỏi", "div[1]/div[8]/?/?/label[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Trộn\\ câu']", 30000, null, "23857d05-a55c-4b34-b875-3e6d3c96e5ad");
                _formcheckInfo = new RepoItemInfo(this, "FormCheck", "div[1]/div[8]/div", 30000, null, "7484a8a9-0051-4a33-8e8b-9f5d14512f14");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("43d5559f-b64d-4596-8b96-712b5f82ee59")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("43d5559f-b64d-4596-8b96-712b5f82ee59")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("086b6bc2-2a40-4e20-b12e-dd9548a4e251")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("086b6bc2-2a40-4e20-b12e-dd9548a4e251")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The ModalBody item.
            /// </summary>
            [RepositoryItem("bfd04f86-3cec-4d42-b2b7-29aff6dc6ac8")]
            public virtual Ranorex.DivTag ModalBody
            {
                get
                {
                    return _modalbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalBody item info.
            /// </summary>
            [RepositoryItemInfo("bfd04f86-3cec-4d42-b2b7-29aff6dc6ac8")]
            public virtual RepoItemInfo ModalBodyInfo
            {
                get
                {
                    return _modalbodyInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("f5ed13d9-9bfb-47ae-85e8-8ec28308e2cb")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("f5ed13d9-9bfb-47ae-85e8-8ec28308e2cb")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The FormGroup item.
            /// </summary>
            [RepositoryItem("74a5b92a-f471-4d38-b5af-eca45d82db85")]
            public virtual Ranorex.DivTag FormGroup
            {
                get
                {
                    return _formgroupInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FormGroup item info.
            /// </summary>
            [RepositoryItemInfo("74a5b92a-f471-4d38-b5af-eca45d82db85")]
            public virtual RepoItemInfo FormGroupInfo
            {
                get
                {
                    return _formgroupInfo;
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarkedNgStarInser item.
            /// </summary>
            [RepositoryItem("aa92ed90-c631-49dd-bb57-1010f783a4fe")]
            public virtual Ranorex.DivTag NgOptionNgOptionMarkedNgStarInser
            {
                get
                {
                    return _ngoptionngoptionmarkedngstarinserInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarkedNgStarInser item info.
            /// </summary>
            [RepositoryItemInfo("aa92ed90-c631-49dd-bb57-1010f783a4fe")]
            public virtual RepoItemInfo NgOptionNgOptionMarkedNgStarInserInfo
            {
                get
                {
                    return _ngoptionngoptionmarkedngstarinserInfo;
                }
            }

            /// <summary>
            /// The Text2 item.
            /// </summary>
            [RepositoryItem("df40a9c2-18d5-47f4-bbcc-f94969f2d501")]
            public virtual Ranorex.InputTag Text2
            {
                get
                {
                    return _text2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text2 item info.
            /// </summary>
            [RepositoryItemInfo("df40a9c2-18d5-47f4-bbcc-f94969f2d501")]
            public virtual RepoItemInfo Text2Info
            {
                get
                {
                    return _text2Info;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("99d5160c-05ee-4843-803e-c71c11006a2a")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("99d5160c-05ee-4843-803e-c71c11006a2a")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The NoItemsFound item.
            /// </summary>
            [RepositoryItem("30fe938d-acd7-46e0-9212-71c003f01506")]
            public virtual Ranorex.DivTag NoItemsFound
            {
                get
                {
                    return _noitemsfoundInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NoItemsFound item info.
            /// </summary>
            [RepositoryItemInfo("30fe938d-acd7-46e0-9212-71c003f01506")]
            public virtual RepoItemInfo NoItemsFoundInfo
            {
                get
                {
                    return _noitemsfoundInfo;
                }
            }

            /// <summary>
            /// The Text3 item.
            /// </summary>
            [RepositoryItem("a6b15461-651d-489f-beb7-261573e1081b")]
            public virtual Ranorex.InputTag Text3
            {
                get
                {
                    return _text3Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text3 item info.
            /// </summary>
            [RepositoryItemInfo("a6b15461-651d-489f-beb7-261573e1081b")]
            public virtual RepoItemInfo Text3Info
            {
                get
                {
                    return _text3Info;
                }
            }

            /// <summary>
            /// The TestClass item.
            /// </summary>
            [RepositoryItem("94561733-7903-469b-9329-f175b8c2e905")]
            public virtual Ranorex.SelectTag TestClass
            {
                get
                {
                    return _testclassInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The TestClass item info.
            /// </summary>
            [RepositoryItemInfo("94561733-7903-469b-9329-f175b8c2e905")]
            public virtual RepoItemInfo TestClassInfo
            {
                get
                {
                    return _testclassInfo;
                }
            }

            /// <summary>
            /// The Number item.
            /// </summary>
            [RepositoryItem("6b2bebca-4952-408f-b6bb-ec474d542f3c")]
            public virtual Ranorex.InputTag Number
            {
                get
                {
                    return _numberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number item info.
            /// </summary>
            [RepositoryItemInfo("6b2bebca-4952-408f-b6bb-ec474d542f3c")]
            public virtual RepoItemInfo NumberInfo
            {
                get
                {
                    return _numberInfo;
                }
            }

            /// <summary>
            /// The Number1 item.
            /// </summary>
            [RepositoryItem("5ff30eec-c807-4d19-b0b1-7dd0cc810aec")]
            public virtual Ranorex.InputTag Number1
            {
                get
                {
                    return _number1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number1 item info.
            /// </summary>
            [RepositoryItemInfo("5ff30eec-c807-4d19-b0b1-7dd0cc810aec")]
            public virtual RepoItemInfo Number1Info
            {
                get
                {
                    return _number1Info;
                }
            }

            /// <summary>
            /// The LabelTagTrộnCauHỏi item.
            /// </summary>
            [RepositoryItem("23857d05-a55c-4b34-b875-3e6d3c96e5ad")]
            public virtual Ranorex.LabelTag LabelTagTrộnCauHỏi
            {
                get
                {
                    return _labeltagtrộncauhỏiInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The LabelTagTrộnCauHỏi item info.
            /// </summary>
            [RepositoryItemInfo("23857d05-a55c-4b34-b875-3e6d3c96e5ad")]
            public virtual RepoItemInfo LabelTagTrộnCauHỏiInfo
            {
                get
                {
                    return _labeltagtrộncauhỏiInfo;
                }
            }

            /// <summary>
            /// The FormCheck item.
            /// </summary>
            [RepositoryItem("7484a8a9-0051-4a33-8e8b-9f5d14512f14")]
            public virtual Ranorex.DivTag FormCheck
            {
                get
                {
                    return _formcheckInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FormCheck item info.
            /// </summary>
            [RepositoryItemInfo("7484a8a9-0051-4a33-8e8b-9f5d14512f14")]
            public virtual RepoItemInfo FormCheckInfo
            {
                get
                {
                    return _formcheckInfo;
                }
            }
        }

        /// <summary>
        /// The ContentBoundFolder folder.
        /// </summary>
        [RepositoryFolder("3b3d24bf-c24e-4590-9722-1bd2a2b854b8")]
        public partial class ContentBoundFolder : RepoGenBaseFolder
        {
            RepoItemInfo _baitậpcuốituầntiếngviệt3tập1Info;
            RepoItemInfo _lớp3Info;
            RepoItemInfo _col9nodenameInfo;
            RepoItemInfo _lớphọccủatoiInfo;
            RepoItemInfo _phonicsInfo;
            RepoItemInfo _kindergartenInfo;

            /// <summary>
            /// Creates a new ContentBound  folder.
            /// </summary>
            public ContentBoundFolder(RepoGenBaseFolder parentFolder) :
                    base("ContentBound", "body/tag[@tagname='app-root']/div[2]", parentFolder, 30000, null, false, "3b3d24bf-c24e-4590-9722-1bd2a2b854b8", "")
            {
                _baitậpcuốituầntiếngviệt3tập1Info = new RepoItemInfo(this, "BaiTậpCuốiTuầnTiếngViệt3Tập1", ".//ul/li[3]/div/div[1]/a[@innertext~'^Bài\\ tập\\ cuối\\ tuần\\ Tiếng\\ V']", 30000, null, "7583a160-6894-4001-a819-027989bf58d9");
                _lớp3Info = new RepoItemInfo(this, "Lớp3", ".//ul/li[6]/div/div[1]/a[@innertext='Lớp 3']", 30000, null, "4d9d17da-16b8-487e-a356-a0e6f2c93034");
                _col9nodenameInfo = new RepoItemInfo(this, "Col9NodeName", "div//ul/li[1]/?/?/div", 30000, null, "a1497206-7c27-4735-9556-447ab887a137");
                _lớphọccủatoiInfo = new RepoItemInfo(this, "LớpHọcCủaToi", "div/div//ul/li[1]//a[@innertext='Lớp học của tôi']", 30000, null, "9edfcdb0-8290-48a5-b086-1e191c1b96b9");
                _phonicsInfo = new RepoItemInfo(this, "PHONICS", "div/div/div/tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div/div[2]/?/?/tag[@tagname='question-preview']/div[1]/div[@innertext='PHONICS']", 30000, null, "f41d4f50-a03c-4c14-b815-b3c9cc5c0e72");
                _kindergartenInfo = new RepoItemInfo(this, "Kindergarten", "div//tag[@tagname='app-list-class']/ul[1]/li/div/div[1]/a[@innertext='Kindergarten']", 30000, null, "ddba55b8-b366-4ff4-83cf-b06068d4f7a7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3b3d24bf-c24e-4590-9722-1bd2a2b854b8")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3b3d24bf-c24e-4590-9722-1bd2a2b854b8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BaiTậpCuốiTuầnTiếngViệt3Tập1 item.
            /// </summary>
            [RepositoryItem("7583a160-6894-4001-a819-027989bf58d9")]
            public virtual Ranorex.ATag BaiTậpCuốiTuầnTiếngViệt3Tập1
            {
                get
                {
                    return _baitậpcuốituầntiếngviệt3tập1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BaiTậpCuốiTuầnTiếngViệt3Tập1 item info.
            /// </summary>
            [RepositoryItemInfo("7583a160-6894-4001-a819-027989bf58d9")]
            public virtual RepoItemInfo BaiTậpCuốiTuầnTiếngViệt3Tập1Info
            {
                get
                {
                    return _baitậpcuốituầntiếngviệt3tập1Info;
                }
            }

            /// <summary>
            /// The Lớp3 item.
            /// </summary>
            [RepositoryItem("4d9d17da-16b8-487e-a356-a0e6f2c93034")]
            public virtual Ranorex.ATag Lớp3
            {
                get
                {
                    return _lớp3Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Lớp3 item info.
            /// </summary>
            [RepositoryItemInfo("4d9d17da-16b8-487e-a356-a0e6f2c93034")]
            public virtual RepoItemInfo Lớp3Info
            {
                get
                {
                    return _lớp3Info;
                }
            }

            /// <summary>
            /// The Col9NodeName item.
            /// </summary>
            [RepositoryItem("a1497206-7c27-4735-9556-447ab887a137")]
            public virtual Ranorex.DivTag Col9NodeName
            {
                get
                {
                    return _col9nodenameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Col9NodeName item info.
            /// </summary>
            [RepositoryItemInfo("a1497206-7c27-4735-9556-447ab887a137")]
            public virtual RepoItemInfo Col9NodeNameInfo
            {
                get
                {
                    return _col9nodenameInfo;
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item.
            /// </summary>
            [RepositoryItem("9edfcdb0-8290-48a5-b086-1e191c1b96b9")]
            public virtual Ranorex.ATag LớpHọcCủaToi
            {
                get
                {
                    return _lớphọccủatoiInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item info.
            /// </summary>
            [RepositoryItemInfo("9edfcdb0-8290-48a5-b086-1e191c1b96b9")]
            public virtual RepoItemInfo LớpHọcCủaToiInfo
            {
                get
                {
                    return _lớphọccủatoiInfo;
                }
            }

            /// <summary>
            /// The PHONICS item.
            /// </summary>
            [RepositoryItem("f41d4f50-a03c-4c14-b815-b3c9cc5c0e72")]
            public virtual Ranorex.DivTag PHONICS
            {
                get
                {
                    return _phonicsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PHONICS item info.
            /// </summary>
            [RepositoryItemInfo("f41d4f50-a03c-4c14-b815-b3c9cc5c0e72")]
            public virtual RepoItemInfo PHONICSInfo
            {
                get
                {
                    return _phonicsInfo;
                }
            }

            /// <summary>
            /// The Kindergarten item.
            /// </summary>
            [RepositoryItem("ddba55b8-b366-4ff4-83cf-b06068d4f7a7")]
            public virtual Ranorex.ATag Kindergarten
            {
                get
                {
                    return _kindergartenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Kindergarten item info.
            /// </summary>
            [RepositoryItemInfo("ddba55b8-b366-4ff4-83cf-b06068d4f7a7")]
            public virtual RepoItemInfo KindergartenInfo
            {
                get
                {
                    return _kindergartenInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("5cad0c60-c7d0-49d9-b14c-44f9b77737ae")]
        public partial class HọcLiệuSachMềmGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _baitậpthựchanhkiểmthửmonint31172Info;
            RepoItemInfo _quaylạiInfo;
            RepoItemInfo _pane1Info;

            /// <summary>
            /// Creates a new HọcLiệuSachMềmGoogleChrome  folder.
            /// </summary>
            public HọcLiệuSachMềmGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềmGoogleChrome", "/form[@title~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']", parentFolder, 30000, null, true, "5cad0c60-c7d0-49d9-b14c-44f9b77737ae", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']/container/container[2]", 30000, null, "61c6dad6-37db-4f9d-b8d5-fbb4c6a6117f");
                _baitậpthựchanhkiểmthửmonint31172Info = new RepoItemInfo(this, "BaiTậpThựcHanhKiểmThửMonINT31172", "container[@accessiblename~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename~'^Bài\\ tập\\ thực\\ hành\\ kiểm\\ th']", 30000, null, "0154edf3-3e5c-4293-b7c7-7f94b0b114d6");
                _quaylạiInfo = new RepoItemInfo(this, "QuayLại", "container[@accessiblename~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']/container[@accessiblename='Google Chrome']//button[@accessiblename='Quay lại']", 30000, null, "afaaf03f-a91e-4840-a2da-25b1be9439b8");
                _pane1Info = new RepoItemInfo(this, "Pane1", "container[@accessiblename~'^Bài\\ tập\\ thực\\ hành\\ kiểm\\ th']/container/container[1]", 30000, null, "473cc4f9-8f1d-4163-a4be-1f8d99b39784");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5cad0c60-c7d0-49d9-b14c-44f9b77737ae")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5cad0c60-c7d0-49d9-b14c-44f9b77737ae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("61c6dad6-37db-4f9d-b8d5-fbb4c6a6117f")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("61c6dad6-37db-4f9d-b8d5-fbb4c6a6117f")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The BaiTậpThựcHanhKiểmThửMonINT31172 item.
            /// </summary>
            [RepositoryItem("0154edf3-3e5c-4293-b7c7-7f94b0b114d6")]
            public virtual Ranorex.TabPage BaiTậpThựcHanhKiểmThửMonINT31172
            {
                get
                {
                    return _baitậpthựchanhkiểmthửmonint31172Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The BaiTậpThựcHanhKiểmThửMonINT31172 item info.
            /// </summary>
            [RepositoryItemInfo("0154edf3-3e5c-4293-b7c7-7f94b0b114d6")]
            public virtual RepoItemInfo BaiTậpThựcHanhKiểmThửMonINT31172Info
            {
                get
                {
                    return _baitậpthựchanhkiểmthửmonint31172Info;
                }
            }

            /// <summary>
            /// The QuayLại item.
            /// </summary>
            [RepositoryItem("afaaf03f-a91e-4840-a2da-25b1be9439b8")]
            public virtual Ranorex.Button QuayLại
            {
                get
                {
                    return _quaylạiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The QuayLại item info.
            /// </summary>
            [RepositoryItemInfo("afaaf03f-a91e-4840-a2da-25b1be9439b8")]
            public virtual RepoItemInfo QuayLạiInfo
            {
                get
                {
                    return _quaylạiInfo;
                }
            }

            /// <summary>
            /// The Pane1 item.
            /// </summary>
            [RepositoryItem("473cc4f9-8f1d-4163-a4be-1f8d99b39784")]
            public virtual Ranorex.Container Pane1
            {
                get
                {
                    return _pane1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane1 item info.
            /// </summary>
            [RepositoryItemInfo("473cc4f9-8f1d-4163-a4be-1f8d99b39784")]
            public virtual RepoItemInfo Pane1Info
            {
                get
                {
                    return _pane1Info;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("6c5492f8-9a4f-47b8-b3b9-7f8809f32dd1")]
        public partial class HọcLiệuSachMềmAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.CreateAssignmentModal1Folder _createassignmentmodal1;
            MyTestRepositoryFolders.ContentBoundFolder1 _contentbound;
            RepoItemInfo _btngroupdropdoitemInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm  folder.
            /// </summary>
            public HọcLiệuSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm", "/dom[11]", parentFolder, 30000, null, false, "6c5492f8-9a4f-47b8-b3b9-7f8809f32dd1", "")
            {
                _createassignmentmodal1 = new MyTestRepositoryFolders.CreateAssignmentModal1Folder(this);
                _contentbound = new MyTestRepositoryFolders.ContentBoundFolder1(this);
                _btngroupdropdoitemInfo = new RepoItemInfo(this, "BtnGroupDropDoItem", ".//button[#'btnGroupDropDoItem']", 30000, null, "76b307b2-d1a8-4b36-abb7-b3d363031d23");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6c5492f8-9a4f-47b8-b3b9-7f8809f32dd1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6c5492f8-9a4f-47b8-b3b9-7f8809f32dd1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnGroupDropDoItem item.
            /// </summary>
            [RepositoryItem("76b307b2-d1a8-4b36-abb7-b3d363031d23")]
            public virtual Ranorex.ButtonTag BtnGroupDropDoItem
            {
                get
                {
                    return _btngroupdropdoitemInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnGroupDropDoItem item info.
            /// </summary>
            [RepositoryItemInfo("76b307b2-d1a8-4b36-abb7-b3d363031d23")]
            public virtual RepoItemInfo BtnGroupDropDoItemInfo
            {
                get
                {
                    return _btngroupdropdoitemInfo;
                }
            }

            /// <summary>
            /// The CreateAssignmentModal1 folder.
            /// </summary>
            [RepositoryFolder("2783b677-90b3-4967-a364-72e00f7a2b6f")]
            public virtual MyTestRepositoryFolders.CreateAssignmentModal1Folder CreateAssignmentModal1
            {
                get { return _createassignmentmodal1; }
            }

            /// <summary>
            /// The ContentBound folder.
            /// </summary>
            [RepositoryFolder("ba159915-2d5d-4c27-9a3b-8169c35f9475")]
            public virtual MyTestRepositoryFolders.ContentBoundFolder1 ContentBound
            {
                get { return _contentbound; }
            }
        }

        /// <summary>
        /// The CreateAssignmentModal1Folder folder.
        /// </summary>
        [RepositoryFolder("2783b677-90b3-4967-a364-72e00f7a2b6f")]
        public partial class CreateAssignmentModal1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _createassignmentmodalInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _modalbodyInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _kindergartenInfo;
            RepoItemInfo _noitemsfoundInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _numberInfo;
            RepoItemInfo _number1Info;
            RepoItemInfo _labeltagtrộncauhỏiInfo;
            RepoItemInfo _ngvaluecontainerInfo;
            RepoItemInfo _ngoptionngoptionmarkedngstarinserInfo;

            /// <summary>
            /// Creates a new CreateAssignmentModal1  folder.
            /// </summary>
            public CreateAssignmentModal1Folder(RepoGenBaseFolder parentFolder) :
                    base("CreateAssignmentModal1", ".//div[#'createAssignmentModal']", parentFolder, 30000, null, false, "2783b677-90b3-4967-a364-72e00f7a2b6f", "")
            {
                _createassignmentmodalInfo = new RepoItemInfo(this, "CreateAssignmentModal", "", 30000, null, "977885fe-184c-418a-8fab-cbe4fe86b3f1");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/?/?/input[@type='submit']", 30000, null, "c0834235-6b3d-4e73-918b-f178d99e8f7c");
                _modalbodyInfo = new RepoItemInfo(this, "ModalBody", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]", 30000, null, "9668fc58-239d-40b9-872d-f7a3bd0c65ac");
                _textInfo = new RepoItemInfo(this, "Text", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[2]/input[@type='text']", 30000, null, "e838fd63-8e30-4057-9434-85241155bba5");
                _kindergartenInfo = new RepoItemInfo(this, "Kindergarten", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/?/?/span[@innertext='Kindergarten']", 30000, null, "02ab5bf6-aeea-4310-b404-9377bf47952e");
                _noitemsfoundInfo = new RepoItemInfo(this, "NoItemsFound", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[4]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div[@innertext='No items found']", 30000, null, "d129b1ed-dc97-4b25-a2d0-227d31036f6e");
                _text1Info = new RepoItemInfo(this, "Text1", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[4]/tag[@tagname='ng-select']/div/div/?/?/input[@type='text']", 30000, null, "50b9fcf9-7c8b-449b-bcda-b8f6bc1d92a8");
                _numberInfo = new RepoItemInfo(this, "Number", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[6]/input[@type='number']", 30000, null, "97be5cf0-c336-4b5e-bda2-5b0552b4f3ea");
                _number1Info = new RepoItemInfo(this, "Number1", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[7]/input[@type='number']", 30000, null, "234a1302-0d58-46c1-bd77-67edeec51699");
                _labeltagtrộncauhỏiInfo = new RepoItemInfo(this, "LabelTagTrộnCauHỏi", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[8]/?/?/label[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Trộn\\ câu']", 30000, null, "986b4f54-c333-4f4f-b479-a94a5ac7a782");
                _ngvaluecontainerInfo = new RepoItemInfo(this, "NgValueContainer", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[3]/tag[@tagname='ng-select']/div/div", 30000, null, "c14f8389-418f-46fd-827a-a51606dc992b");
                _ngoptionngoptionmarkedngstarinserInfo = new RepoItemInfo(this, "NgOptionNgOptionMarkedNgStarInser", ".//form[@action='https://hoclieu.sachmem.vn/question_set/5b431dcb4d16f43900ac55fc/5ba07366753dd2ef285b0d9e/preview']/div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div", 30000, null, "7d9bb063-c55c-4239-9a4f-7384fd5318f2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2783b677-90b3-4967-a364-72e00f7a2b6f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2783b677-90b3-4967-a364-72e00f7a2b6f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateAssignmentModal item.
            /// </summary>
            [RepositoryItem("977885fe-184c-418a-8fab-cbe4fe86b3f1")]
            public virtual Ranorex.DivTag CreateAssignmentModal
            {
                get
                {
                    return _createassignmentmodalInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CreateAssignmentModal item info.
            /// </summary>
            [RepositoryItemInfo("977885fe-184c-418a-8fab-cbe4fe86b3f1")]
            public virtual RepoItemInfo CreateAssignmentModalInfo
            {
                get
                {
                    return _createassignmentmodalInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("c0834235-6b3d-4e73-918b-f178d99e8f7c")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("c0834235-6b3d-4e73-918b-f178d99e8f7c")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The ModalBody item.
            /// </summary>
            [RepositoryItem("9668fc58-239d-40b9-872d-f7a3bd0c65ac")]
            public virtual Ranorex.DivTag ModalBody
            {
                get
                {
                    return _modalbodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalBody item info.
            /// </summary>
            [RepositoryItemInfo("9668fc58-239d-40b9-872d-f7a3bd0c65ac")]
            public virtual RepoItemInfo ModalBodyInfo
            {
                get
                {
                    return _modalbodyInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("e838fd63-8e30-4057-9434-85241155bba5")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("e838fd63-8e30-4057-9434-85241155bba5")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Kindergarten item.
            /// </summary>
            [RepositoryItem("02ab5bf6-aeea-4310-b404-9377bf47952e")]
            public virtual Ranorex.SpanTag Kindergarten
            {
                get
                {
                    return _kindergartenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Kindergarten item info.
            /// </summary>
            [RepositoryItemInfo("02ab5bf6-aeea-4310-b404-9377bf47952e")]
            public virtual RepoItemInfo KindergartenInfo
            {
                get
                {
                    return _kindergartenInfo;
                }
            }

            /// <summary>
            /// The NoItemsFound item.
            /// </summary>
            [RepositoryItem("d129b1ed-dc97-4b25-a2d0-227d31036f6e")]
            public virtual Ranorex.DivTag NoItemsFound
            {
                get
                {
                    return _noitemsfoundInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NoItemsFound item info.
            /// </summary>
            [RepositoryItemInfo("d129b1ed-dc97-4b25-a2d0-227d31036f6e")]
            public virtual RepoItemInfo NoItemsFoundInfo
            {
                get
                {
                    return _noitemsfoundInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("50b9fcf9-7c8b-449b-bcda-b8f6bc1d92a8")]
            public virtual Ranorex.InputTag Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("50b9fcf9-7c8b-449b-bcda-b8f6bc1d92a8")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The Number item.
            /// </summary>
            [RepositoryItem("97be5cf0-c336-4b5e-bda2-5b0552b4f3ea")]
            public virtual Ranorex.InputTag Number
            {
                get
                {
                    return _numberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number item info.
            /// </summary>
            [RepositoryItemInfo("97be5cf0-c336-4b5e-bda2-5b0552b4f3ea")]
            public virtual RepoItemInfo NumberInfo
            {
                get
                {
                    return _numberInfo;
                }
            }

            /// <summary>
            /// The Number1 item.
            /// </summary>
            [RepositoryItem("234a1302-0d58-46c1-bd77-67edeec51699")]
            public virtual Ranorex.InputTag Number1
            {
                get
                {
                    return _number1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number1 item info.
            /// </summary>
            [RepositoryItemInfo("234a1302-0d58-46c1-bd77-67edeec51699")]
            public virtual RepoItemInfo Number1Info
            {
                get
                {
                    return _number1Info;
                }
            }

            /// <summary>
            /// The LabelTagTrộnCauHỏi item.
            /// </summary>
            [RepositoryItem("986b4f54-c333-4f4f-b479-a94a5ac7a782")]
            public virtual Ranorex.LabelTag LabelTagTrộnCauHỏi
            {
                get
                {
                    return _labeltagtrộncauhỏiInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The LabelTagTrộnCauHỏi item info.
            /// </summary>
            [RepositoryItemInfo("986b4f54-c333-4f4f-b479-a94a5ac7a782")]
            public virtual RepoItemInfo LabelTagTrộnCauHỏiInfo
            {
                get
                {
                    return _labeltagtrộncauhỏiInfo;
                }
            }

            /// <summary>
            /// The NgValueContainer item.
            /// </summary>
            [RepositoryItem("c14f8389-418f-46fd-827a-a51606dc992b")]
            public virtual Ranorex.DivTag NgValueContainer
            {
                get
                {
                    return _ngvaluecontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgValueContainer item info.
            /// </summary>
            [RepositoryItemInfo("c14f8389-418f-46fd-827a-a51606dc992b")]
            public virtual RepoItemInfo NgValueContainerInfo
            {
                get
                {
                    return _ngvaluecontainerInfo;
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarkedNgStarInser item.
            /// </summary>
            [RepositoryItem("7d9bb063-c55c-4239-9a4f-7384fd5318f2")]
            public virtual Ranorex.DivTag NgOptionNgOptionMarkedNgStarInser
            {
                get
                {
                    return _ngoptionngoptionmarkedngstarinserInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarkedNgStarInser item info.
            /// </summary>
            [RepositoryItemInfo("7d9bb063-c55c-4239-9a4f-7384fd5318f2")]
            public virtual RepoItemInfo NgOptionNgOptionMarkedNgStarInserInfo
            {
                get
                {
                    return _ngoptionngoptionmarkedngstarinserInfo;
                }
            }
        }

        /// <summary>
        /// The ContentBoundFolder1 folder.
        /// </summary>
        [RepositoryFolder("ba159915-2d5d-4c27-9a3b-8169c35f9475")]
        public partial class ContentBoundFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _giaobaitậpInfo;
            RepoItemInfo _fafalgfahomeInfo;
            RepoItemInfo _baitậpcuốituầntiếnganh3tập1Info;

            /// <summary>
            /// Creates a new ContentBound  folder.
            /// </summary>
            public ContentBoundFolder1(RepoGenBaseFolder parentFolder) :
                    base("ContentBound", "body/tag[@tagname='app-root']/div[2]", parentFolder, 30000, null, false, "ba159915-2d5d-4c27-9a3b-8169c35f9475", "")
            {
                _giaobaitậpInfo = new RepoItemInfo(this, "GiaoBaiTập", ".//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div/div[1]/div[2]/a[@href='javascript:void(0)']/span[@innertext='Giao bài tập']", 30000, null, "9b116ad1-8f81-4252-9c8a-5a6d6d3e48b5");
                _fafalgfahomeInfo = new RepoItemInfo(this, "FaFaLgFaHome", ".//tag[@tagname='question']/div/div[2]/ol/li[2]/a[@href~'^https://hoclieu\\.sachmem\\.v']/i", 30000, null, "5624b056-f7ca-4981-b97b-2690a1aaf426");
                _baitậpcuốituầntiếnganh3tập1Info = new RepoItemInfo(this, "BaiTậpCuốiTuầnTiếngAnh3Tập1", ".//ul/li[2]/div/div[1]/a[@innertext~'^Bài\\ Tập\\ Cuối\\ Tuần\\ Tiếng\\ A']", 30000, null, "371342e5-354c-480d-b81f-9623501e98a5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba159915-2d5d-4c27-9a3b-8169c35f9475")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba159915-2d5d-4c27-9a3b-8169c35f9475")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiaoBaiTập item.
            /// </summary>
            [RepositoryItem("9b116ad1-8f81-4252-9c8a-5a6d6d3e48b5")]
            public virtual Ranorex.SpanTag GiaoBaiTập
            {
                get
                {
                    return _giaobaitậpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GiaoBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("9b116ad1-8f81-4252-9c8a-5a6d6d3e48b5")]
            public virtual RepoItemInfo GiaoBaiTậpInfo
            {
                get
                {
                    return _giaobaitậpInfo;
                }
            }

            /// <summary>
            /// The FaFaLgFaHome item.
            /// </summary>
            [RepositoryItem("5624b056-f7ca-4981-b97b-2690a1aaf426")]
            public virtual Ranorex.ITag FaFaLgFaHome
            {
                get
                {
                    return _fafalgfahomeInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaLgFaHome item info.
            /// </summary>
            [RepositoryItemInfo("5624b056-f7ca-4981-b97b-2690a1aaf426")]
            public virtual RepoItemInfo FaFaLgFaHomeInfo
            {
                get
                {
                    return _fafalgfahomeInfo;
                }
            }

            /// <summary>
            /// The BaiTậpCuốiTuầnTiếngAnh3Tập1 item.
            /// </summary>
            [RepositoryItem("371342e5-354c-480d-b81f-9623501e98a5")]
            public virtual Ranorex.ATag BaiTậpCuốiTuầnTiếngAnh3Tập1
            {
                get
                {
                    return _baitậpcuốituầntiếnganh3tập1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BaiTậpCuốiTuầnTiếngAnh3Tập1 item info.
            /// </summary>
            [RepositoryItemInfo("371342e5-354c-480d-b81f-9623501e98a5")]
            public virtual RepoItemInfo BaiTậpCuốiTuầnTiếngAnh3Tập1Info
            {
                get
                {
                    return _baitậpcuốituầntiếnganh3tập1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
