///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("6ea15d6d-542f-4b7f-80ca-e589eee83937", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://hoclieu.sachmem.vn/folder/0' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://hoclieu.sachmem.vn/folder/0", "chrome", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GiaoBaiTập' at 85;9.", repo.ApplicationUnderTest.GiaoBaiTậpInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.GiaoBaiTập.Click("85;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody' at 600;322.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBodyInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody.MoveTo("600;322");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody' at 596;180.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBodyInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody.MoveTo("596;180");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody' at 608;319.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBodyInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody.MoveTo("608;319");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody' at 597;37.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBodyInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.ModalBody.MoveTo("597;37");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text' at 214;22.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.TextInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text.Click("214;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 11}' with focus on 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.TextInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text.PressKeys("{Back 11}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.FormGroup' at 258;35.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.FormGroupInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.FormGroup.Click("258;35");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text1' at 212;30.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text1Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text1.Click("212;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text2' at 212;30.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text2Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text2.Click("212;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarkedNgStarInser' at 386;5.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarkedNgStarInserInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NgOptionNgOptionMarkedNgStarInser.Click("386;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text3' at 172;11.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text3Info, new RecordItemIndex(12));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text3.Click("172;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jhjfjgh' with focus on 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text3'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text3Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Text3.PressKeys("jhjfjgh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NoItemsFound' at 123;16.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NoItemsFoundInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NoItemsFound.Click("123;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '0: 1' on item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.TestClass'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.TestClassInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.TestClass.Element.SetAttributeValue("TagValue", "0: 1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number' at 138;13.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number.Click("138;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '-1' with focus on 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number.PressKeys("-1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number1' at 139;20.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number1Info, new RecordItemIndex(21));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number1.Click("139;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10' with focus on 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number1'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number1Info, new RecordItemIndex(22));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number1.PressKeys("10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number' at 157;34.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number.Click("157;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number' at 28;34.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number.Click("28;34");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number'.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.NumberInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Number.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.LabelTagTrộnCauHỏi' at 78;22.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.LabelTagTrộnCauHỏiInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.LabelTagTrộnCauHỏi.Click("78;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(27));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(28));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(29));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(30));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(31));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Submit' at 22;11.", repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.SubmitInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.HttpsHoclieuSachmemVnQuestionSet.Submit.Click("22;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (HasFocus='False') on item 'HọcLiệuSachMềmGoogleChrome.Pane'.", repo.HọcLiệuSachMềmGoogleChrome.PaneInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.HọcLiệuSachMềmGoogleChrome.PaneInfo, "HasFocus", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'HọcLiệuSachMềmGoogleChrome.Pane'.", repo.HọcLiệuSachMềmGoogleChrome.PaneInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.HọcLiệuSachMềmGoogleChrome.PaneInfo, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'HọcLiệuSachMềmGoogleChrome.Pane'.", repo.HọcLiệuSachMềmGoogleChrome.PaneInfo, new RecordItemIndex(35));
            Validate.AttributeEqual(repo.HọcLiệuSachMềmGoogleChrome.PaneInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềmGoogleChrome.BaiTậpThựcHanhKiểmThửMonINT31172' at 41;2.", repo.HọcLiệuSachMềmGoogleChrome.BaiTậpThựcHanhKiểmThửMonINT31172Info, new RecordItemIndex(36));
            repo.HọcLiệuSachMềmGoogleChrome.BaiTậpThựcHanhKiểmThửMonINT31172.Click("41;2");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
